// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using WpfApp1;
//
//    var sectionRu = SectionRu.FromJson(jsonString);

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SectionRu
    {
        [JsonProperty("sorting")]
        public long Sorting { get; set; }

        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("text")]
        public string Text { get; set; }
    }

    public partial class SectionRu
    {
        public static SectionRu[] FromJson(string json) => JsonConvert.DeserializeObject<SectionRu[]>(json, WpfApp1.ConverterSection.Settings);
    }

    public static class SerializeSection
    {
        public static string ToJson(this SectionRu[] self) => JsonConvert.SerializeObject(self, WpfApp1.ConverterSection.Settings);
    }

    internal static class ConverterSection
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
